In [1]:
import numpy as np

In [2]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is 2E3D-90D7

 Directory of C:\Users\LENOVO\revision1

07/28/2024  01:35 AM    <DIR>          .
07/26/2024  04:10 PM    <DIR>          ..
07/28/2024  01:28 AM    <DIR>          .ipynb_checkpoints
07/28/2024  01:30 AM               806 numpy assignmet.ipynb
07/28/2024  01:28 AM            97,830 numpyrevision.ipynb
06/19/2024  07:30 AM               988 president_heights.csv
               3 File(s)         99,624 bytes
               3 Dir(s)  173,176,606,720 bytes free


In [7]:
data=np.genfromtxt('president_heights.csv',delimiter=',', skip_header=1, dtype=None, encoding='utf-8', invalid_raise=False)


In [8]:
data

array([( 1, 'George Washington', 189), ( 2, 'John Adams', 170),
       ( 3, 'Thomas Jefferson', 189), ( 4, 'James Madison', 163),
       ( 5, 'James Monroe', 183), ( 6, 'John Quincy Adams', 171),
       ( 7, 'Andrew Jackson', 185), ( 8, 'Martin Van Buren', 168),
       ( 9, 'William Henry Harrison', 173), (10, 'John Tyler', 183),
       (11, 'James K. Polk', 173), (12, 'Zachary Taylor', 173),
       (13, 'Millard Fillmore', 175), (14, 'Franklin Pierce', 178),
       (15, 'James Buchanan', 183), (16, 'Abraham Lincoln', 193),
       (17, 'Andrew Johnson', 178), (18, 'Ulysses S. Grant', 173),
       (19, 'Rutherford B. Hayes', 174), (20, 'James A. Garfield', 183),
       (21, 'Chester A. Arthur', 183), (23, 'Benjamin Harrison', 168),
       (25, 'William McKinley', 170), (26, 'Theodore Roosevelt', 178),
       (27, 'William Howard Taft', 182), (28, 'Woodrow Wilson', 180),
       (29, 'Warren G. Harding', 183), (30, 'Calvin Coolidge', 178),
       (31, 'Herbert Hoover', 182), (32, 'Frankli

In [9]:
data.shape

(42,)

In [11]:
data[0:6]

array([(1, 'George Washington', 189), (2, 'John Adams', 170),
       (3, 'Thomas Jefferson', 189), (4, 'James Madison', 163),
       (5, 'James Monroe', 183), (6, 'John Quincy Adams', 171)],
      dtype=[('f0', '<i4'), ('f1', '<U22'), ('f2', '<i4')])

In [17]:
data.dtype

dtype([('f0', '<i4'), ('f1', '<U22'), ('f2', '<i4')])

In [19]:
orders=data['f0']
names=data['f1']
height=data['f2']

In [20]:
orders

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44])

In [21]:
np.where(orders=='NaN')

(array([], dtype=int64),)

### AVERAGE OF THE PREISDENT HEIGHTS

In [22]:
avg=np.mean(height)

In [23]:
avg

179.73809523809524

### max height

In [24]:
np.max(height)

193

### min height

In [25]:
np.min(height)

163

In [30]:
for m in height:
    if(m>180):
        print(n)
        

['George Washington' 'John Adams' 'Thomas Jefferson' 'James Madison'
 'James Monroe' 'John Quincy Adams' 'Andrew Jackson' 'Martin Van Buren'
 'William Henry Harrison' 'John Tyler' 'James K. Polk' 'Zachary Taylor'
 'Millard Fillmore' 'Franklin Pierce' 'James Buchanan' 'Abraham Lincoln'
 'Andrew Johnson' 'Ulysses S. Grant' 'Rutherford B. Hayes'
 'James A. Garfield' 'Chester A. Arthur' 'Benjamin Harrison'
 'William McKinley' 'Theodore Roosevelt' 'William Howard Taft'
 'Woodrow Wilson' 'Warren G. Harding' 'Calvin Coolidge' 'Herbert Hoover'
 'Franklin D. Roosevelt' 'Harry S. Truman' 'Dwight D. Eisenhower'
 'John F. Kennedy' 'Lyndon B. Johnson' 'Richard Nixon' 'Gerald Ford'
 'Jimmy Carter' 'Ronald Reagan' 'George H. W. Bush' 'Bill Clinton'
 'George W. Bush' 'Barack Obama']
['George Washington' 'John Adams' 'Thomas Jefferson' 'James Madison'
 'James Monroe' 'John Quincy Adams' 'Andrew Jackson' 'Martin Van Buren'
 'William Henry Harrison' 'John Tyler' 'James K. Polk' 'Zachary Taylor'
 'Millard

In [31]:
filtered=height>180

In [32]:
filtered

array([ True, False,  True, False,  True, False,  True, False, False,
        True, False, False, False, False,  True,  True, False, False,
       False,  True,  True, False, False, False,  True, False,  True,
       False,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True])

In [33]:
fp=data[filtered]

In [34]:
fp

array([( 1, 'George Washington', 189), ( 3, 'Thomas Jefferson', 189),
       ( 5, 'James Monroe', 183), ( 7, 'Andrew Jackson', 185),
       (10, 'John Tyler', 183), (15, 'James Buchanan', 183),
       (16, 'Abraham Lincoln', 193), (20, 'James A. Garfield', 183),
       (21, 'Chester A. Arthur', 183), (27, 'William Howard Taft', 182),
       (29, 'Warren G. Harding', 183), (31, 'Herbert Hoover', 182),
       (32, 'Franklin D. Roosevelt', 188), (35, 'John F. Kennedy', 183),
       (36, 'Lyndon B. Johnson', 193), (37, 'Richard Nixon', 182),
       (38, 'Gerald Ford', 183), (40, 'Ronald Reagan', 185),
       (41, 'George H. W. Bush', 188), (42, 'Bill Clinton', 188),
       (43, 'George W. Bush', 182), (44, 'Barack Obama', 185)],
      dtype=[('f0', '<i4'), ('f1', '<U22'), ('f2', '<i4')])

### President less than height 170 cm

In [35]:
lh=height<170

In [36]:
lh

array([False, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [37]:
fpp=data[lh]

In [38]:
fpp

array([( 4, 'James Madison', 163), ( 8, 'Martin Van Buren', 168),
       (23, 'Benjamin Harrison', 168)],
      dtype=[('f0', '<i4'), ('f1', '<U22'), ('f2', '<i4')])